In [1]:
from imutils import paths
import os
import numpy as np

In [2]:
a = np.arange(20).reshape(4, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
b = np.sum(a, axis=0)

In [5]:
a * b

array([[  0,  34,  76, 126, 184],
       [150, 204, 266, 336, 414],
       [300, 374, 456, 546, 644],
       [450, 544, 646, 756, 874]])

In [6]:
b

array([30, 34, 38, 42, 46])

In [7]:
np.array(b).reshape(5, 1)

array([[30],
       [34],
       [38],
       [42],
       [46]])

In [8]:
jokes = [('www1', [[1, 2, 3, 4, 5],[2 ,3 ,4 ,5, 6]]),('www2', [[2, 5, 6, 7,1], [3, 6, 9, 0, 1]])]

In [9]:
dess = jokes[0][1]

In [10]:
for w, joke in jokes[1:]:
    dess = np.vstack((dess, joke ))

In [11]:
dess

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [2, 5, 6, 7, 1],
       [3, 6, 9, 0, 1]])

In [12]:
I = np.arange(20).reshape(4, 5)

In [13]:
I.shape[1:2]

(5,)

In [15]:
c = a.copy()

In [16]:
(c == a).all()

True

In [17]:
a = []

In [18]:
a=['a', 'b', 'v', 'c', 'z']

In [19]:
np.array(a).reshape(-1, 1)

array([['a'],
       ['b'],
       ['v'],
       ['c'],
       ['z']], dtype='<U1')

In [20]:
path = '/Users/zhangxiao/Desktop/数据/训练数据/'
name = os.listdir(path)

In [21]:
name

['.DS_Store',
 '看不清',
 '夜间装土无帆布遮盖',
 '夜间空车无帆布遮盖',
 '夜间有帆布遮盖',
 '白天空车无帆布遮盖',
 '白天有帆布遮盖',
 '白天装土无帆布遮盖']