In [2]:
import numpy as np
from collections import Counter
import pandas as pd
from imblearn.over_sampling import SMOTE
import random

In [4]:
data = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/crx.data', dtype = str)
data = data.replace('?', np.nan) # 用数字替换符号
data = data.replace('+', 1)
data = data.replace('-', 0)
# copy1 = data.iloc[:30, :]
# copy2 = data.iloc[-30:, :]
# data = data.append(copy1,ignore_index=True)
# data = data.append(copy2,ignore_index=True)

xData = data.iloc[:, :-1]
yLabel = data.iloc[:, -1]

In [ ]:
xData.info()

In [5]:
xData.isnull().sum().sort_values(ascending=False)

A14    13
A2     12
A1     12
A7      9
A6      9
A5      6
A4      6
A15     0
A13     0
A12     0
A11     0
A10     0
A9      0
A8      0
A3      0
dtype: int64

In [ ]:
xData

In [3]:
xData[['A2', 'A3', 'A8', 'A11', 'A14','A15']] = xData[['A2', 'A3', 'A8', 'A11', 'A14','A15']].astype('float')

In [ ]:
xData.dtypes

In [31]:
xDataM1 = xData.loc[:, ['A2', 'A3', 'A8', 'A11', 'A14', 'A15']]
xDataM2 = xData.loc[:, ['A1', 'A4', 'A5', 'A6', 'A7', 'A9', 'A10', 'A12', 'A13']]

#### 处理xDataM1（数值型数据）

In [32]:
for column in list(xDataM1.columns[xDataM1.isnull().sum() > 0]): # 用均值填补NaN
    mean_val = round(xDataM1[column].mean(), 2)
    xDataM1[column] = xDataM1[column].fillna(mean_val)

In [ ]:
xDataM1.isnull().sum() > 0

#### 处理xDataM2(类别型数据）

In [33]:
for col in list(xDataM2.columns[xDataM2.isnull().sum() > 0]): # 用众数填补空值
    xDataM2[col] = xDataM2[col].fillna(xDataM2[col].mode()[0])

In [ ]:
print(xDataM2[xDataM2.isnull().T.any()])

In [34]:
for col in xDataM2.columns.values.tolist(): # 将符号数字化
    xDataM2[col] = pd.factorize(xDataM2[col])[0].astype(np.int)

In [ ]:
xDataM2

In [ ]:
xDataM2.columns.values.tolist()# 获取colums名

In [ ]:
x1 = np.arange(3, 9).reshape((1, 6))
x2 = np.arange(4, 10). reshape((1, 6))

In [ ]:
d =  np.argwhere(x1 != x2)

In [ ]:
d1 = np.argwhere(xDataM2[0] != xDataM2[1])

In [ ]:
len(d1)

In [ ]:
count = [2, 1, 2, 2, 2, 2, 2, 4, 5, 1, 1, 1, 5, 1, 1,4]

In [ ]:
max(count, key=count.count)

In [ ]:
max(set(count), key=count.count)

### 复制加值

In [ ]:
yLabel

In [ ]:
datax = np.array(data)

In [ ]:
datax

In [ ]:
len(np.argwhere(datax[:, -1] == 1))

In [ ]:
len(np.argwhere(datax[:, -1] == 0))

In [9]:
num = np.array([72.57,72.57,66.86,73.14,67.43,72.57,69.71,72,69.71,68])

In [10]:
np.std(num,ddof=1)

2.4089564361173283

In [11]:
np.mean(num)

70.45599999999999

In [45]:
qa = np.array([[91.43,90.86,90.86,90.29,90.29,90.29,89.71,90.29,89.71],
              [86.29,86.29,85.14,85.14,85.71,86.29,87.43,86.29,86.86],
              [80.57,81.14,81.14,81.14,81.14,80.57,80.00,80.57,80.57],
              [85.71,85.71,85.71,85.71,85.71,85.71,85.71,85.71,85.14],
              [82.86,82.86,82.86,82.86,82.86,83.43,83.43,85.14,86.86],
              [89.71,89.71,89.14,88.57,88.57,89.14,89.71,90.29,89.71],
              [88.57,88.57,88.57,88.57,88.57,88.57,88.57,88.57,89.71],
              [89.14,89.14,89.14,89.14,89.14,89.71,89.71,90.29,90.29],
              [85.14,85.14,84.57,84.57,84.57,84.57,84.57,85.14,86.29],
              [93.14,93.14,93.14,93.14,93.14,92.00,92.00,92.57,90.29]])

In [46]:
qa.mean(0)

array([87.256, 87.256, 87.027, 86.913, 86.97 , 87.028, 87.084, 87.486,
       87.543])

### SMOTE算法

In [35]:
xDataM1 = np.array(xDataM1)
xDataM2 = np.array(xDataM2)
yLabel = np.array(yLabel)

In [36]:
tempxData = np.hstack((xDataM1, xDataM2))

In [37]:
smo = SMOTE(sampling_strategy={1:438, 0:437}, random_state=5)

In [38]:
tempxData, yLabel = smo.fit_sample(tempxData, yLabel)

/Users/zhangxiao/anaconda3/anaconda3/lib/python3.7/site-packages/imblearn/utils/_validation.py:285: UserWarning: After over-sampling, the number of samples (438) in class 1 will be larger than the number of samples in the majority class (class #0 -> 383)
  n_samples_majority,
/Users/zhangxiao/anaconda3/anaconda3/lib/python3.7/site-packages/imblearn/utils/_validation.py:285: UserWarning: After over-sampling, the number of samples (437) in class 0 will be larger than the number of samples in the majority class (class #0 -> 383)
  n_samples_majority,


In [39]:
print(Counter(yLabel))

Counter({1: 438, 0: 437})


In [13]:
tempxData[:5]

array([[3.083e+01, 0.000e+00, 1.250e+00, 1.000e+00, 2.020e+02, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00],
       [5.867e+01, 4.460e+00, 3.040e+00, 6.000e+00, 4.300e+01, 5.600e+02,
        1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00],
       [2.450e+01, 5.000e-01, 1.500e+00, 0.000e+00, 2.800e+02, 8.240e+02,
        1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00],
       [2.783e+01, 1.540e+00, 3.750e+00, 5.000e+00, 1.000e+02, 3.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00],
       [2.017e+01, 5.625e+00, 1.710e+00, 0.000e+00, 1.200e+02, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 1.000e+00]])

In [14]:
xDataM1[:5]

array([[3.083e+01, 0.000e+00, 1.250e+00, 1.000e+00, 2.020e+02, 0.000e+00],
       [5.867e+01, 4.460e+00, 3.040e+00, 6.000e+00, 4.300e+01, 5.600e+02],
       [2.450e+01, 5.000e-01, 1.500e+00, 0.000e+00, 2.800e+02, 8.240e+02],
       [2.783e+01, 1.540e+00, 3.750e+00, 5.000e+00, 1.000e+02, 3.000e+00],
       [2.017e+01, 5.625e+00, 1.710e+00, 0.000e+00, 1.200e+02, 0.000e+00]])

In [15]:
xDataM2[:5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1]])

In [16]:
random.seed(5)
list1 = random.sample(range(118, 215),55)
list2 = random.sample(range(601, 689), 54)

In [17]:
for i in list1:
    tempxData = np.vstack((tempxData, tempxData[i]))
    yLabel = np.hstack((yLabel, yLabel[i]))

In [18]:
len(tempxData)
len(yLabel)

825

In [19]:
for i in list2:
    tempxData = np.vstack((tempxData, tempxData[i]))
    yLabel = np.hstack((yLabel, yLabel[i]))

In [20]:
len(tempxData)
len(yLabel)

875

In [22]:
xDataM1 = tempxData[:, :6]

In [23]:
xDataM2 = tempxData[:, 6:]

In [24]:
Counter(yLabel)

Counter({1: 442, 0: 433})

In [25]:
xDataM1

array([[3.083e+01, 0.000e+00, 1.250e+00, 1.000e+00, 2.020e+02, 0.000e+00],
       [5.867e+01, 4.460e+00, 3.040e+00, 6.000e+00, 4.300e+01, 5.600e+02],
       [2.450e+01, 5.000e-01, 1.500e+00, 0.000e+00, 2.800e+02, 8.240e+02],
       ...,
       [3.225e+01, 1.400e+01, 0.000e+00, 2.000e+00, 1.600e+02, 1.000e+00],
       [3.108e+01, 1.500e+00, 4.000e-02, 0.000e+00, 1.600e+02, 0.000e+00],
       [3.233e+01, 3.500e+00, 5.000e-01, 0.000e+00, 2.320e+02, 0.000e+00]])

In [3]:
p = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/trial.csv')

In [10]:
data = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/trial.csv', dtype=str)
data = data.astype('float')

xData = data.iloc[:, :-1]
yLabel = data.iloc[:, -1]



In [11]:
np.isnan(xData).any()

Sector_score     False
LOCATION_ID      False
PARA_A           False
SCORE_A          False
PARA_B           False
SCORE_B          False
TOTAL            False
numbers          False
Marks            False
Money_Value       True
MONEY_Marks      False
District         False
Loss             False
LOSS_SCORE       False
History          False
History_score    False
Score            False
dtype: bool