In [1]:
import numpy as np
import pandas as pd
import random

In [ ]:
random.seed(10)
random.sample(range(0, 10), 10)

In [ ]:
random.seed(10)
random.sample(range(0, 10), 10)

In [ ]:
random.seed(10)
random.sample(range(0,6), 6)

In [ ]:
random.seed(10)
random.sample(range(0,6), 6)

In [ ]:
random.seed(10)
print(random.sample(range(0, 10), 10))
print(random.sample(range(0, 6), 6))

In [ ]:
random.seed(10)
print(random.sample(range(0, 10), 10))
print(random.sample(range(0, 6), 6))

In [ ]:
random.seed(10)
print(random.sample(range(0, 10), 10))
print(random.sample(range(0, 6), 6))

In [ ]:
random.seed(10)
random.sample(range(0,6), 6)

In [ ]:
random.seed(10)
print(random.sample(range(0, 6), 6))
print(random.sample(range(0, 10), 10))

In [4]:
a1 = np.arange(10).reshape(2, 5)

In [5]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
a2 = np.arange(10, 20).reshape(2, 5)

In [8]:
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
a1[1] = a2[1]

In [12]:
a1

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [31]:
random.sample(range(0, 5), 3)

[3, 1, 2]