#### Hepatitis data process

In [ ]:
import numpy as np
from collections import Counter
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
import random

In [ ]:
data = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/hepatitis.data',header=None, dtype = str)
data = data.rename(columns={0:'Class',1:'AGE', 2:'SEX', 3:'STEROID', 4:'ANTIVIRALS', 5:'FATIGUE', 6:'MALAISE', 
                            7:'ANOREXIA', 8:'LIVER BIG', 9:'LIVER FIRM', 10:'SPLEEN PALPABLE', 11:'SPIDERS', 
                            12:'ASCITES', 13:'VARICES', 14:'BILIRUBIN', 15:'ALK PHOSPHATE', 16:'SGOT', 17:'ALBUMIN', 
                            18:'PROTIME', 19:'HISTOLOGY'})
data = data.replace('?', np.nan) # 用数字替换"?"字符

In [ ]:
xData = data.iloc[:, 1:]
yLabel = data.iloc[:, 0]

In [ ]:
xData.head()

In [ ]:
xData.isnull().sum().sort_values(ascending=False)

In [ ]:
xData[['AGE','BILIRUBIN','ALK PHOSPHATE','SGOT','ALBUMIN','PROTIME']] = xData[['AGE','BILIRUBIN','ALK PHOSPHATE','SGOT','ALBUMIN','PROTIME']].astype('float')

In [ ]:
xData.dtypes

In [ ]:
xDataM0 = xData.loc[:, ['AGE', 'BILIRUBIN', 'ALK PHOSPHATE', 'SGOT', 'ALBUMIN','PROTIME']]
xDataM1 = xData.loc[:, ['SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE', 'ANOREXIA', 
                        'LIVER BIG', 'LIVER FIRM', 'SPLEEN PALPABLE', 'SPIDERS', 'ASCITES',
                        'VARICES', 'HISTOLOGY']]

#### 处理数值型数据

In [ ]:
for column in list(xDataM0.columns[xDataM0.isnull().sum() > 0]): # 用均值填补NaN
    mean_val = round(xDataM0[column].mean(), 2)
    xDataM0[column] = xDataM0[column].fillna(mean_val)

In [ ]:
xDataM0.isnull().sum() > 0

In [ ]:
xDataM0.head()

#### 处理类别型数据

In [ ]:
for col in list(xDataM1.columns[xDataM1.isnull().sum() > 0]): # 用中位数填补空值
    xDataM1[col] = xDataM1[col].fillna(xDataM1[col].mode()[0])

In [ ]:
xDataM1.isnull().sum() > 0

In [ ]:
xDataM1.apply(pd.value_counts)

In [ ]:
c = [0, 2, 5, 6, 8, 10, 11]
xDataM1.drop(xDataM1.columns[c], axis=1, inplace=True) 

In [ ]:
xDataM1.head()

In [ ]:
xDataM0 = np.array(xDataM0)
xDataM1 = np.array(xDataM1)
yLabel = np.array(yLabel)

In [ ]:
tempxData = np.hstack((xDataM0, xDataM1))

In [ ]:
smo = SMOTE(random_state=5)

In [ ]:
tempxData, yLabel = smo.fit_sample(tempxData, yLabel)

In [ ]:
print(Counter(yLabel))

#### Heart data process

In [ ]:
import numpy as np
from collections import Counter
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
import random

In [ ]:
data = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/heart.dat', sep='\s+', header=None, dtype = str)

In [ ]:
xData = data.iloc[:, :-1]
yLabel = data.iloc[:, -1]

In [ ]:
xData.head()

In [ ]:
yLabel.head()

In [ ]:
xDataM0 = xData.loc[:, [0, 3, 5, 7, 9, 11]]
xDataM1 = xData.loc[:, [1, 2, 4, 6, 8, 10, 12]]

In [ ]:
xDataM0 = xDataM0.astype('float')

In [ ]:
xDataM0.dtypes

In [ ]:
xDataM0 = np.array(xDataM0)
xDataM1 = np.array(xDataM1)
yLabel = np.array(yLabel)

In [ ]:
tempxData = np.hstack((xDataM0, xDataM1))

In [ ]:
smo = SMOTE(random_state=5)

In [ ]:
tempxData, yLabel = smo.fit_sample(tempxData, yLabel)

In [ ]:
print(Counter(yLabel))

#### Bands data process

In [1]:
import numpy as np
from collections import Counter
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
import random

In [2]:
data = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/bands.data',header=None, dtype = str)

In [3]:
c = [0, 1, 2, 3]
data.drop(data.columns[c], axis=1, inplace=True)

data = data.replace('?', np.nan) # 用数字替换"?"字符

In [4]:
xData = data.iloc[:, :-1]
yLabel = data.iloc[:, -1]

In [ ]:
xData.head()

In [5]:
xDataM0 = xData.iloc[:, 16:]
xDataM1 = xData.iloc[:, :16]

In [6]:
xDataM0.head()

20  21     22  23  24      25  26    27    28    29    30 31 32   33   34  \
0  55  46    0.2  17  78    0.75  20  13.1  1700  50.5  36.4  0  0  2.5    1   
1  55  46    0.3  15  80    0.75  20   6.6  1900  54.9  38.5  0  0  2.5  0.7   
2  62  40  0.433  16  80     NaN  30   6.5  1850  53.8  39.8  0  0  2.8  0.9   
3  52  40    0.3  16  75  0.3125  30   5.6  1467  55.6  38.8  0  0  2.5  1.3   
4  50  46    0.3  17  80    0.75  30     0  2100  57.5  42.5  5  0  2.3  0.6   

   35  36      37   38  
0  34  40     105  100  
1  34  40     105  100  
2  40  40  103.87  100  
3  40  40  108.06  100  
4  35  40  106.67  100

In [7]:
xDataM0 = xDataM0.astype('float')

In [8]:
xDataM1.head()

4    5    6       7         8         9         10  11    12   13  \
0  YES  KEY  YES  BENTON  GALLATIN  UNCOATED  UNCOATED  NO  LINE  YES   
1  YES  KEY  YES  BENTON  GALLATIN  UNCOATED  UNCOATED  NO  LINE  YES   
2  YES  KEY  YES  BENTON  GALLATIN  UNCOATED    COATED  NO  LINE  YES   
3  YES  KEY  YES  BENTON  GALLATIN  UNCOATED  UNCOATED  NO  LINE  YES   
4   NO  KEY  YES  BENTON  GALLATIN  UNCOATED    COATED  NO  LINE  YES   

          14   15 16       17       18    19  
0   Motter94  821  2  TABLOID  NorthUS  1911  
1   Motter94  821  2  TABLOID  NorthUS   NaN  
2  WoodHoe70  815  9  CATALOG  NorthUS   NaN  
3  WoodHoe70  816  9  CATALOG  NorthUS  1910  
4  WoodHoe70  816  2  TABLOID      NaN  1910

In [ ]:
list(xDataM0.columns[xDataM0.isnull().sum() > 0])

In [9]:
xDataM0 = xDataM0.copy()
for col in list(xDataM0.columns[xDataM0.isnull().sum() > 0]): # 用均值填补NaN
    mean_val = round(xDataM0[col].mean(), 2)
    xDataM0[col] = xDataM0[col].fillna(mean_val)

In [ ]:
xDataM0.head()

In [ ]:
xDataM1.head()

In [ ]:
list(xDataM1.columns[xDataM1.isnull().sum() > 0])

In [10]:
xDataM1 = xDataM1.copy()
for col in list(xDataM1.columns[xDataM1.isnull().sum() > 0]): # 用众数填补空值
    fill_value = xData[col].mode()[0]
    xDataM1[col] = xDataM1[col].fillna(fill_value)

In [11]:
for col in xDataM1.columns.values.tolist(): # 将符号数字化
    xDataM1[col] = pd.factorize(xDataM1[col])[0].astype(np.int)

In [ ]:
xDataM0.head()

In [ ]:
xDataM1.head()

In [ ]:
xDataM0.isnull().sum() > 0

In [ ]:
xDataM1.isnull().sum() > 0

In [12]:
xDataM0 = np.array(xDataM0)
xDataM1 = np.array(xDataM1)
yLabel = np.array(yLabel)

In [13]:
tempxData = np.hstack((xDataM0, xDataM1))

In [14]:
smo = SMOTE(random_state=5)

In [15]:
tempxData, yLabel = smo.fit_sample(tempxData, yLabel)

In [16]:
print(Counter(yLabel))

Counter({'band': 312, 'noband': 312})


In [17]:
xDataM0 = tempxData[:, :19]
xDataM1 = tempxData[:, 19:]

In [18]:
xDataM0[:5, :]

array([[5.5000e+01, 4.6000e+01, 2.0000e-01, 1.7000e+01, 7.8000e+01,
        7.5000e-01, 2.0000e+01, 1.3100e+01, 1.7000e+03, 5.0500e+01,
        3.6400e+01, 0.0000e+00, 0.0000e+00, 2.5000e+00, 1.0000e+00,
        3.4000e+01, 4.0000e+01, 1.0500e+02, 1.0000e+02],
       [5.5000e+01, 4.6000e+01, 3.0000e-01, 1.5000e+01, 8.0000e+01,
        7.5000e-01, 2.0000e+01, 6.6000e+00, 1.9000e+03, 5.4900e+01,
        3.8500e+01, 0.0000e+00, 0.0000e+00, 2.5000e+00, 7.0000e-01,
        3.4000e+01, 4.0000e+01, 1.0500e+02, 1.0000e+02],
       [6.2000e+01, 4.0000e+01, 4.3300e-01, 1.6000e+01, 8.0000e+01,
        7.2000e-01, 3.0000e+01, 6.5000e+00, 1.8500e+03, 5.3800e+01,
        3.9800e+01, 0.0000e+00, 0.0000e+00, 2.8000e+00, 9.0000e-01,
        4.0000e+01, 4.0000e+01, 1.0387e+02, 1.0000e+02],
       [5.2000e+01, 4.0000e+01, 3.0000e-01, 1.6000e+01, 7.5000e+01,
        3.1250e-01, 3.0000e+01, 5.6000e+00, 1.4670e+03, 5.5600e+01,
        3.8800e+01, 0.0000e+00, 0.0000e+00, 2.5000e+00, 1.3000e+00,
        4.000

In [19]:
xDataM1[:5, :]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 2., 0., 0., 0., 1.]])

In [ ]:
yLabel = pd.factorize(yLabel)[0].astype(np.int)

In [ ]:
yLabel

#### Horse data process

In [1]:
import numpy as np
from collections import Counter
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
import random

In [ ]:
data1 = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/horse-colic.data',sep='\s+', 
                   header=None, dtype=str)
data2 = pd.read_csv('/Users/zhangxiao/Desktop/论文测试数据集/horse-colic.test', sep='\s+',
                   header=None, dtype=str)
print(len(data1))
print(len(data2))

In [ ]:
data = pd.concat([data1, data2], axis=0)
print(len(data))

In [ ]:
data.head()

In [ ]:
c = [2, 24, 25, 26]
data.drop(data.columns[c], axis=1, inplace=True)

data = data.replace('?', np.nan) # 用数字替换"?"字符

In [ ]:
xData = data.iloc[:, :-1]
yLabel = data.iloc[:, -1]

In [ ]:
xDataM0 = xData.loc[:, [3,4,5,15,18,19,21]]
xDataM1 = xData.loc[:, [0,1,6,7,8,9,10,11,12,13,14,16,17,20,22,23]]

In [ ]:
xDataM0.head()

In [ ]:
xDataM1.head()

In [ ]:
xDataM0 = xDataM0.astype('float')

In [ ]:
xDataM0 = xDataM0.copy()
for col in list(xDataM0.columns[xDataM0.isnull().sum() > 0]): # 用均值填补NaN
    mean_val = round(xDataM0[col].mean(), 2)
    xDataM0[col] = xDataM0[col].fillna(mean_val)

In [ ]:
xDataM1 = xDataM1.copy()
for col in list(xDataM1.columns[xDataM1.isnull().sum() > 0]): # 用众数填补空值
    fill_value = xData[col].mode()[0]
    xDataM1[col] = xDataM1[col].fillna(fill_value)

In [ ]:
xDataM0.head()

In [ ]:
xDataM1.head()

In [ ]:
xDataM0 = np.array(xDataM0)
xDataM1 = np.array(xDataM1)
yLabel = np.array(yLabel)

In [ ]:
tempxData = np.hstack((xDataM0, xDataM1))

In [ ]:
smo = SMOTE(random_state=5)

In [ ]:
tempxData, yLabel = smo.fit_sample(tempxData, yLabel)

In [ ]:
Counter(yLabel)

In [ ]:
yLabel = yLabel.astype('int')

In [ ]:
yLabel

In [3]:
r = np.array([[83.3,83.3,83.3,83.3,81.67,81.67,80,80,78.33],
             [85,85,85,83.33,83.33,81.67,81.67,81.67,81.67],
             [88.33,88.33,88.33,88.33,88.33,88.33,88.33,88.33,88.33],
             [86.67,86.67,86.67,86.67,86.67,86.67,86.67,86.67,86.67],
             [86.67,86.67,86.67,86.67,86.67,85,85,83.33,83.33],
             [76.67,76.67,76.67,76.67,76.67,76.67,76.67,76.67,76.67],
             [83.33,83.33,83.33,83.33,83.33,83.33,81.67,81.67,81.67],
             [83.33,83.33,83.33,83.33,83.33,83.33,85,85,83.33],
             [76.67,76.67,76.67,76.67,76.67,76.67,76.67,76.67,76.67],
             [81.67,81.67,81.67,81.67,81.67,81.67,81.67,81.67,81.67]])

In [4]:
r.mean(0)

array([83.164, 83.164, 83.164, 82.997, 82.834, 82.501, 82.335, 82.168,
       81.834])